# Generated by Django 3.0 on 2020-08-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('fruit', models.CharField(max_length=20, verbose_name='果物')),
                ('num', models.PositiveIntegerField(verbose_name='個数')),
                ('sum', models.PositiveIntegerField(verbose_name='売り上げ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('num', models.PositiveIntegerField(verbose_name='個数')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.Fruits', verbose_name='果物')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
