# Generated by Django 3.1 on 2020-08-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinfo',
            name='num',
            field=models.PositiveIntegerField(verbose_name='個数'),
        ),
        migrations.AlterField(
            model_name='soldinfo',
            name='num',
            field=models.PositiveIntegerField(verbose_name='個数'),
        ),
        migrations.AlterField(
            model_name='soldinfo',
            name='sum',
            field=models.PositiveIntegerField(verbose_name='売り上げ'),
        ),
    ]
